### ISSUE TITLE
Accessing the version number of ciscoconfparse that is installed

### ISSUE THREAD

**Issue by gmuloc** [mpenning/ciscoconfparse#120]
Not something too bothering, I think but thought I would flag it here as it caused one of my scripts to fail.

I have a script checking that ciscoconfparse version installed on the system is above some value (1.2.39)

```
>>> import ciscoconfparse
>>> ciscoconfparse.version.__version__
'1.2.49'
```

```
>>> ciscoconfparse.ciscoconfparse.__version__
'1.3.20'
>>> ciscoconfparse.version.__version__
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
AttributeError: 'module' object has no attribute 'version'
```

While I can easily fix it in my code thought I would mention this here. It was introduced in https://github.com/mpenning/ciscoconfparse/commit/7caadc34daec6398182ea74d39cbf0813c53744e when the version file stopped being imported.

**Comment by mpenning** [comment]
Hello,

Python provides an API to get which version of a module you have installed...

```
>>> import pkg_resources
>>> pkg_resources.get_distribution('ciscoconfparse').version
'1.3.20'
>>>
```

This should work, regardless of what version of ciscoconfparse you have installed
