### ISSUE TITLE
geneology_text throwing error when returning non parent config

### ISSUE THREAD

**Issue by vrnaveenkr** [mpenning/ciscoconfparse#214]
geneology_text throwing error when returning non parent config. the same script works in version 1.6.4 but not in 1.6.6 and 1.6.7.

Error Glimpse : 
if line_origin.geneology_text == line_target.geneology_text
v\lib\site-packages\ciscoconfparse\ccp_abc.py", line 898, in geneology_text
    retval.append(self.text)
AttributeError: 'map' object has no attribute 'append'

**Comment by mpenning** [comment]
Hello,

Thank you for reporting this problem.  However, according to `git blame ccp_abc.py` the script line and method you're referencing (in ccp_abc.py) has not changed since March of 2015.  Unless I'm mistaken, many ciscoconfparse versions had this bug (all versions since March 2015).

I can reproduce the reported bug.  I added some basic unit tests to detect the problem.  This bug is fixed in version 1.6.8.  I still have a couple more things to do before I release 1.6.8 on pypi... I'll release 1.6.8 later today.

Kind Regards,
\mike

**Comment by vrnaveenkr** [comment]
Hello @mpenning 
Tons of thanks for the information and quick response. Waiting for the new version. This repo is doing a lot's of help to me..

**Comment by mpenning** [comment]
You're most welcome @vrnaveenkr
